### ISSUE TITLE
Link to pretrained models is dead?

### ISSUE THREAD

**Issue by ikb-a** [ronghanghu/snmn#11]
Hi, great work! I hate to ask, but I think the link to the pretrained models is now dead?

https://people.eecs.berkeley.edu/~ronghang/projects/snmn/pretrained_models/exp_vqa/tfmodel/

Any chance the pretrained models are still available somewhere? Thanks!

**Comment by ronghanghu** [comment]
Sorry that the links expired. I've uploaded the models here: https://drive.google.com/drive/folders/152Ad_dX5cS5gBYYToBy9jgN9OI-9Cumw?usp=sharing

**Comment by ikb-a** [comment]
Thanks! :)
