### ISSUE TITLE
CLEVR-Ref dataset cannot be found

### ISSUE THREAD

**Issue by zinccat** [ronghanghu/snmn#13]
The [link](http://people.eecs.berkeley.edu/~ronghang/projects/snmn/CLEVR_loc.tgz) is dead, please update it, thanks!

**Comment by ronghanghu** [comment]
Hi @zinccat, sorry that the previous link has expired. I've uploaded it here: https://drive.google.com/file/d/1e_4ESvU6IMFAeVxMXAJhSdGJdPdwxnwH/view?usp=sharing

**Comment by zinccat** [comment]
Thanks!
