### ISSUE TITLE
Link to pre-trained models dead

### ISSUE THREAD

**Issue by zachary-cauchi** [ronghanghu/snmn#14]
Hi @ronghanghu. I'm trying to download the pre-trained models for clevr and vqa but the link provided (https://people.eecs.berkeley.edu/~ronghang/projects/snmn/pretrained_models/exp_vqa/tfmodel/) is dead. Would you still happen to have them available?

**Comment by ronghanghu** [comment]
Hi @zachary-cauchi, sorry that the links have expired. I've uploaded the models here: https://drive.google.com/drive/folders/15EYBymzexMQ12GEq5cG6nabw7-CunaZ0?usp=sharing

**Comment by zachary-cauchi** [comment]
Hi @ronghanghu. Thanks a lot for the new link! Closing the issue.
