### ISSUE TITLE
Problem in test

### ISSUE THREAD

**Issue by trx14** [ronghanghu/snmn#9]
When I run the test code, I faced this error "ImportError: cannot import name 'merge_cfg_from_file' ". I checked the models_clevr_snmn.config file, and change the function name from "merge_cfg_from_file" to  "_merge_cfg_from_file" and it work. Is this a bug or I make some mistakes?

**Comment by ronghanghu** [comment]
This seems to be a typo in the code release. I'll fix it in the repo. Thanks for reporting it!
